OnlineOrderingSystem/OnlineOrderingSystem/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace OnlineOrderingSystem.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        [DisplayName("Image")]
        public IFormFile ImageFile { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public ICollection<Comment> Comments { get; set; }
        
        public int HowMany { get; set; }

        public bool CommentsEnabled { get; set; } = true;
        public bool ShowFlag { get; set; } = false;

        public ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

      

        public ICollection<ProductOption> ProductOptions { get; set; } = new List<ProductOption>();

    }
}

OnlineOrderingSystem/OnlineOrderingSystem/Models/Wishlist.cs
namespace OnlineOrderingSystem.Models
{
    public class Wishlist
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public User User { get; set; } 
        public int ProductId { get; set; } 
        public Product Product { get; set; } 
    }
}

OnlineOrderingSystem/OnlineOrderingSystem/ViewModels/ProductViewModel.cs
public class ProductViewModel
{
    public string Name { get; set; }
    public string Description { get; set; }
    public decimal Price { get; set; }
    public int CategoryId { get; set; }
    public bool HasDiscount { get; set; }
    public int HowMany { get; set; }

    public decimal DiscountPrice { get; set; }
    public List<IFormFile> ImageFiles { get; set; } = new List<IFormFile>();
    public List<ProductOptionViewModel> ProductOptions { get; set; } = new List<ProductOptionViewModel>();
}

public class ProductOptionViewModel
{
    public string OptionName { get; set; }
    public decimal OptionPrice { get; set; }
}
    

OnlineOrderingSystem/OnlineOrderingSystem/ViewModels/WishlistViewModel.cs
using OnlineOrderingSystem.Models;

public class WishlistViewModel
{
    public List<Product> Products { get; set; }
    public List<Wishlist> UserWishlists { get; set; }

}

OnlineOrderingSystem/OnlineOrderingSystem/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using OnlineOrderingSystem.Data;
using OnlineOrderingSystem.Models;
using OnlineOrderingSystem.ViewModels;

namespace OnlineOrderingSystem.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<User> _userManager;

        public ProductsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, UserManager<User> userManager)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _userManager = userManager;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Products.Include(p => p.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> DetailsProducts(int? id, int loadCount = 2)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Comments)
                .ThenInclude(c => c.user)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }
            var loadCounts = 20;
            // Get similar products based on the category
            var similarProducts = await _context.Products
                .Where(p => p.CategoryId == product.CategoryId && p.Id != id)
                .Take(4)
                .ToListAsync();
            var comments = product.Comments.Take(loadCount).ToList();
            ViewBag.TotalComments = product.Comments.Count;
            ViewBag.LoadCount = loadCount;
            ViewBag.Comments = comments;
            ViewBag.SimilarProducts = similarProducts;
            return View("DetailsProducts", product);
        }

        [HttpGet]
        public IActionResult GetMoreComments(int productId, int loadCount)
        {
            var comments = _context.Comments
                .Where(c => c.ProductId == productId)
                .Include(c => c.user)
                .Skip(loadCount).Take(4).ToList();

            return Ok(comments.Select(c => new
            {
                c.user.UserName,
                c.Content,
                c.user.Avatar
            }));
        }

        public IActionResult CreateProduct()
        {
            ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProducts(Product product)
        {
            
                // Handle image upload
                if (product.ImageFile != null)
                {
                    var fileName = Path.GetFileNameWithoutExtension(product.ImageFile.FileName);
                    var extension = Path.GetExtension(product.ImageFile.FileName);
                    product.Image = fileName + "_" + DateTime.Now.ToString("yyyyMMddHHmmss") + extension;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", product.Image);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await product.ImageFile.CopyToAsync(fileStream);
                    }
                }

                // Add product to the database
                _context.Add(product);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Admin");
            

        }

        public async Task<IActionResult> Wishlist()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var products = await _context.Products
                .Include(p => p.ProductOptions)
                .ToListAsync();

            var userWishlists = await _context.Wishlists
                .Where(w => w.UserId == userId)
                .Include(w => w.Product)
                .Include(w => w.User)
                .ToListAsync();

            ViewBag.Products = products;
            ViewBag.UserWishlists = userWishlists;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edite(int id, [Bind("Id,Name,Description,Price,Image,CategoryId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", product.CategoryId);
            return View(product);
        }

        [HttpPost]
        public IActionResult Search(string query)
        {
            if (!string.IsNullOrEmpty(query))
            {
                var products = _context.Products
                    .Where(p => p.Name.Contains(query))
                    .Select(p => new
                    {
                        p.Id,
                        p.Name,
                        p.Description,
                        p.Price,
                        p.Image,
                        p.CategoryId,
                        CategoryName = p.Category.Name
                    })
                    .ToList();
                return Ok(products);
            }
            return Ok(Enumerable.Empty<object>());
        }

        [HttpPost]
        public async Task<IActionResult> CreateComment(string Content, int id)
        {
            var product = await _context.Products.FindAsync(id);

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Comment comment1 = new Comment();

            comment1.DatePosted = DateTime.Now;
            comment1.UserId = userId;
            comment1.ProductId = id;
            comment1.Product = product;
            comment1.Content = Content;
            _context.Add(comment1);
            await _context.SaveChangesAsync();
            return RedirectToAction("DetailsProducts", "Products", new { id = id });
        }

        [HttpPost]
        public IActionResult ToggleCommentsEnabled(int id)
        {
            var product = _context.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            product.CommentsEnabled = !product.CommentsEnabled;
            _context.SaveChanges();

            return RedirectToAction("Index", "Admin");
        }
        [HttpPost]
        public IActionResult ToggleShowFlag(int id)
        {
            var product = _context.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            product.ShowFlag = !product.ShowFlag;
            _context.SaveChanges();

            return RedirectToAction("AdminProducts", "Admin");
        }

        public async Task<IActionResult> TopProuct()
        {
            var topProductIds = await _context.Wishlists
                .GroupBy(w => w.ProductId)
                .OrderByDescending(g => g.Count())
                .Select(g => g.Key)
                .Take(5)
                .ToListAsync();

            var topProducts = await _context.Products
                .Where(p => topProductIds.Contains(p.Id))
                .Take(5)  
                .ToListAsync();

            return View(topProducts);
        }


        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Products.FindAsync(id);
            if (item != null)
            {
                _context.Products.Remove(item);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Admin");
        }

        public async Task<IActionResult> EditProducts(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category) // Include related entities if needed
                .FirstOrDefaultAsync(p => p.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            // Populate categories for dropdown
            ViewBag.CategoryId = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name", product.CategoryId);

            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProducts(int id, Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (product.ImageFile != null && product.ImageFile.Length > 0)
            {
                var fileName = Path.GetFileName(product.ImageFile.FileName);

OnlineOrderingSystem/OnlineOrderingSystem/Controllers/WishlistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineOrderingSystem.Data;
using OnlineOrderingSystem.Models;

namespace OnlineOrderingSystem.Controllers
{
    public class WishlistsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WishlistsController(ApplicationDbContext context)
        {
               _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var wishlists = await _context.Wishlists
                .Include(w => w.Product)
                .Where(w => w.UserId == userId)
                .ToListAsync();

            return View(wishlists);
        }


        public async Task<IActionResult> ToggleWishlist(int productId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var existingWishlist = await _context.Wishlists
                .FirstOrDefaultAsync(w => w.UserId == userId && w.ProductId == productId);

            if (existingWishlist != null)
            {
                _context.Wishlists.Remove(existingWishlist);
                await _context.SaveChangesAsync();
                return Json(new { success = true, isAdded = false, message = "Product removed from wishlist successfully." });
            }
            else
            {
                var wishlist = new Wishlist
                {
                    UserId = userId,
                    ProductId = productId
                };

                _context.Wishlists.Add(wishlist);
                await _context.SaveChangesAsync();
                return Json(new { success = true, isAdded = true, message = "Product added to wishlist successfully." });
            }
        }



    }
}

OnlineOrderingSystem/OnlineOrderingSystem/Views/Products/CreateProduct.cshtml
@model OnlineOrderingSystem.Models.Product
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Create Product</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateProducts" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="HowMany" class="control-label"></label>
                <input asp-for="HowMany" class="form-control" />
                <span asp-validation-for="HowMany" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Image" class="control-label">Cover Image</label>
                <input asp-for="ImageFile" class="form-control" type="file" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>

        
          

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


    <script>
      
    </script>

OnlineOrderingSystem/OnlineOrderingSystem/Views/Products/EditProducts.cshtml
@model OnlineOrderingSystem.Models.Product

@{
    ViewData["Title"] = "Edit Product";
}

<h1>Edit Product</h1>
<div>
    <form asp-action="EditProducts" asp-controller="Products" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <textarea asp-for="Description" class="form-control" rows="4"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="control-label"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="ImageFile" class="control-label">Upload Image</label>
            <input asp-for="ImageFile" type="file" class="form-control-file" />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CategoryId" class="control-label"></label>
            <select asp-for="CategoryId" asp-items="ViewBag.CategoryId" class="form-control"></select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="HowMany" class="control-label"></label>
            <input asp-for="HowMany" class="form-control" />
            <span asp-validation-for="HowMany" class="text-danger"></span>
        </div>

        <div class="form-group">
            <div class="form-check">
                <input asp-for="CommentsEnabled" type="checkbox" class="form-check-input" />
                <label asp-for="CommentsEnabled" class="form-check-label"></label>
            </div>
            <span asp-validation-for="CommentsEnabled" class="text-danger"></span>
        </div>

        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

OnlineOrderingSystem/OnlineOrderingSystem/Views/Products/GetMoreComments.cshtml
@model List<Comment>
@{
    Layout = null;
}
<div>
    @foreach (var comment in Model)
    {
        <li>@comment.Content - <strong>@comment.user</strong></li>
        <img src="@comment.user.Avatar" />
    }
</div>

OnlineOrderingSystem/OnlineOrderingSystem/Views/Products/TopProuct.cshtml
@model IEnumerable<OnlineOrderingSystem.Models.Product>

<div id="category-details-container" class="product-list">
    <div>
        <h6>Top product</h6>

    </div>
    <div class="product-gorup">
        @foreach (var product in Model)
        {
            <div class="product-card">
                <div class="card product-item border-0 mb-4 w-100">
                    <div class="product-image-container">
                        <img class="product-image" src="~/images/@product.Image" alt="@product.Name">
                        <div class="footerend">
                            <a href="@Url.Action("DetailsProducts", "Products", new { id = product.Id })" class="btn btn-sm text-dark p-0">
                                <span class="icon-wrapper">
                                    <i class="fas fa-eye"></i>
                                </span>
                            </a>
                        </div>

                    </div>
                    <div class="card-body">

                        <div class="product-Name">
                            <h6 class="text-truncate mb-3">@product.Name</h6>
                        </div>
                        <div class="product-price">


                            <div class="price">
                                <h6><p class="card-text"><strong>Price:</strong> <span id="price-@product.Id">@product.Price.ToString("C")</span></p></h6>
                                <h6><p class="card-text">@product.HowMany pice</p></h6>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

</div>
<style>


    .product-list {
        display: flex;
        gap: 2rem;
        justify-content: center;
        flex-direction: column;
        width:100%;
    }

    .product-gorup {
        display: flex;
        gap: 20px;
    }

    .product-card {
        display: flex;
        flex-direction: row;
        gap: 1rem;
        border: 2px solid rgba(228, 228, 288, 0.9);
        border-radius: 15px;
        width: 250px;
        height: 300px;
        opacity: 0;
        transform: translateY(20px);
        transition: opacity 0.5s ease-out, transform 0.5s ease-out;
    }

        .product-card.in-view {
            opacity: 1;
            transform: translateY(0);
        }

    .product-image-container {
        position: relative;
        width: 100%;
        height: 20rem;
        overflow: hidden;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .product-image {
        padding: 20px;
        max-width: 100%;
        max-height: 100%;
        object-fit: cover;
        border-radius: 0.5rem;
        transition: opacity 0.5s ease, transform 0.5s ease;
    }

        .product-image:hover {
            transform: scale(1.1);
        }

    .footerend {
        position: absolute;
        bottom: 10px;
        left: 50%;
        transform: translateX(-50%);
        opacity: 0;
        transition: opacity 0.5s ease;
    }

    .product-image-container:hover .footerend {
        opacity: 1;
    }

    .product-details {
        display: flex;
        justify-content: space-between;
    }

    .card-body {
        display: flex;
        gap: 10px;
        flex-direction: column;
    }

    .icon-wrapper {
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: white;
        color: gray;
        border-radius: 4px;
        padding: 5px;
        border: 2px solid rgba(228, 228, 288);
    }

        .icon-wrapper i {
            color: gray;
            margin-right: 5px; /* Space between icon and text */
        }

    .price {
        display: flex;
        justify-content: space-between;
    }
</style>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        let observerOptions = {
            root: null,
            rootMargin: "0px",
            threshold: 0.1
        };

        let observer = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add("in-view");
                    observer.unobserve(entry.target);
                }
            });
        }, observerOptions);

        document.querySelectorAll(".product-card").forEach(card => {
            observer.observe(card);
        });
    });
</script>

OnlineOrderingSystem/OnlineOrderingSystem/Views/Products/Wishlist.cshtml
@model WishlistViewModel
@{
    Layout = null;
}




<script>

    function updatePrice(productId, optionPrice) {
        var priceElement = document.getElementById('price-' + productId);
        priceElement.textContent = optionPrice.toFixed(2);
    }

    function AddToCart(productId) {
        var selectedOption = document.querySelector('input[name="option-' + productId + '"]:checked');
        var optionId = selectedOption ? selectedOption.getAttribute('data-option-id') : null;
        var optionPrice = selectedOption ? parseFloat(selectedOption.value) : null;

        $.ajax({
            url: '@Url.Action("AddToCart", "Carts")',
            type: 'POST',
            data: {
                productId: productId,
                optionId: optionId,
                optionPrice: optionPrice
            },
            success: function (response) {
                if (response.success) {
                    toastr.success(response.message);
                } else {
                    toastr.error(response.message);
                }
            },
            error: function (error) {
                toastr.error('Failed to add product to cart', error);
            }
        });
    }

    function toggleWishlist(productId) {
        var btn = $('#btnWishlist_' + productId);
        var icon = $('#iconWishlist_' + productId);

        $.ajax({
            type: "POST",
            url: '@Url.Action("ToggleWishlist", "Wishlists")',
            data: { productId: productId },
            success: function (response) {
                if (response.success) {
                    if (response.isAdded) {
                        icon.removeClass('fa fa-heart').addClass('fa fa-heart text-danger');
                        toastr.success(response.message);
                    } else {
                        icon.removeClass('bi-calendar-heart-fill text-danger').addClass('bi-calendar-heart');
                        toastr.success(response.message);
                    }
                } else {
                    toastr.error(response.message);
                }
            },
            error: function () {
                toastr.error("An error occurred while toggling the product in the wishlist.");
            }
        });
    }
</script>




<style>
    .btn-wishlist-added {
        background-color: #ffc107 !important;
        color: #212529 !important;
    }
</style>
<div class="col-lg-9 col-md-12">
    <div class="row pb-3 post-card">
        @foreach (var product in ViewBag.Products as List<Product>)
        {
            <div class="product-card">
                <div class="card product-item border-0 mb-4">
                    <img class="productImage w-100" src="~/images/@product.Image" alt="@product.Name">

                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">@product.Name</h6>
                        <h6><p class="card-text"><strong>Price:</strong> <span id="price-@product.Id">@product.Price.ToString("C")</span></p></h6>
                        @if (product.ProductOptions != null && product.ProductOptions.Count > 0)
                        {
                            <ul class="list-unstyled">
                                @foreach (var option in product.ProductOptions)
                                {
                                    <li>
                                        <input type="radio" name="option-@product.Id" value="@option.OptionPrice" data-product-id="@product.Id" data-option-id="@option.Id" onchange="updatePrice(@product.Id, @option.OptionPrice)"> @option.OptionName: @option.OptionPrice.ToString("C")
                                    </li>
                                }
                            </ul>
                        }
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="@Url.Action("DetailsProducts", "Products", new { id = product.Id })" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>

                        @{
                            var userWishlists = ViewBag.UserWishlists as List<Wishlist>;
                            bool isInWishlist = userWishlists != null && userWishlists.Any(w => w.ProductId == product.Id);
                            string iconClass = isInWishlist ? "fa fa-heart text-danger" : "fa fa-heart";
                        }

                        <button id="btnWishlist_@product.Id" class="btn btn-sm text-dark p-0 ml-2" onclick="toggleWishlist(@product.Id)">
                            <i id="iconWishlist_@product.Id" class="@iconClass"></i>
                        </button>

                        <button type="button" onclick="AddToCart(@product.Id)" class="btn btn-sm text-dark p-0 ml-2">Add to Cart</button>
                    </div>
                </div>
            </div>
        }

        <div class="col-12 pb-1">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center mb-3">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<style>
    .post-card {
        border: 1px solid black;
        width: 900px;
        margin-top: 3rem;
        display: flex;
        gap: 2rem;
        padding: 20px;
        box-shadow:
    }

    .product-card {
        width: 16rem;
        height: 32rem;
        border-radius: 10px;
        overflow: hidden;
        cursor: pointer;
        box-shadow: 0 10px 30px 5px rgba(0, 0, 0, 0.2);
    }

    .productImage {
        object-fit: cover;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        opacity: 0.9;
        transition: opacity .2s ease-out;
    }

        .productImage:hover {
            transition: opacity .3s ease-in;
            opacity: 1;
        }
</style>