OnlineOrderingSystem/OnlineOrderingSystem/Models/Cart.cs
namespace OnlineOrderingSystem.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public User user { get; set; }
        public ICollection<CartItem> CartItems { get; set; }

       
    }
}

OnlineOrderingSystem/OnlineOrderingSystem/ViewModels/CartViewModel.cs
namespace OnlineOrderingSystem.ViewModels
{
    public class CartViewModel
    {
        public string Email { get; set; }
         public string Avatar { get; set; }
        public List<CartItemViewModel> CartItems { get; set; }
    }

    public class CartItemViewModel
    {
        public int CartItemId { get; set; }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; } 
        public decimal TotalPrice => Quantity * Price;

        public string? Image { get; internal set; }
        public List<ProductOptionViewModel> ProductOptions { get; set; }
    }
}

OnlineOrderingSystem/OnlineOrderingSystem/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineOrderingSystem.Data;
using OnlineOrderingSystem.Migrations;
using OnlineOrderingSystem.Models;
using OnlineOrderingSystem.ViewModels;

namespace OnlineOrderingSystem.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public CartsController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> CartMenu()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            string userId = user.Id;
            var userCart = _context.Carts
                .Include(c => c.user)
                .Include(c => c.CartItems)
                    .ThenInclude(ci => ci.Product)
                .FirstOrDefault(c => c.UserId == userId);

            if (userCart == null)
            {
                userCart = new Cart
                {
                    UserId = userId,
                    user = user,
                    CartItems = new List<CartItem>()
                };

                _context.Carts.Add(userCart);
                await _context.SaveChangesAsync();
            }

            var cartViewModel = new CartViewModel
            {
                Email = userCart.user?.Email,
                Avatar = userCart.user?.Avatar,
                CartItems = userCart.CartItems.Select(ci => new CartItemViewModel
                {
                    CartItemId = ci.Id,
                    ProductId = ci.ProductId,
                    ProductName = ci.Product.Name,
                    Quantity = ci.Quantity,
                    Price = ci.Price,
                    Image = ci.Product.Image
                }).ToList()
            };

            return View(cartViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Checkout(string selectedPaymentMethod)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Json(new { error = "User not logged in" });
            }

            string userId = currentUser.Id;
            var order = new Order { UserId = userId, OrderDate = DateTime.Now, Status = "Pending" };

            var cartItems = _context.CartItems.Where(ci => ci.Cart.UserId == currentUser.Id).ToList();
            _context.Orders.Add(order);
            foreach (var cartItem in cartItems)
            {
                var orderItem = new OrderItem
                {
                    Order = order,
                    ProductId = cartItem.ProductId,
                    Quantity = cartItem.Quantity,
                    Price = cartItem.Price
                };
                _context.OrderItems.Add(orderItem);
            }

            order.TotalPrice = order.OrderItems.Sum(oi => oi.Quantity * oi.Price);

            var payment = new Payment
            {
                Order = order,
                Amount = order.TotalPrice,
                PaymentDate = DateTime.Now,
                PaymentMethod = selectedPaymentMethod,
                Status = "Success"
            };
            _context.Payments.Add(payment);

            _context.CartItems.RemoveRange(cartItems);
            await _context.SaveChangesAsync();

            return Json(new { orderId = order.Id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, int? optionId, decimal? optionPrice)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                string userId = user.Id;
                var cart = _context.Carts.Include(c => c.CartItems).FirstOrDefault(c => c.UserId == userId);

                if (cart == null)
                {
                    cart = new Cart
                    {
                        UserId = userId,
                        user = user
                    };
                    _context.Carts.Add(cart);
                }

                var product = _context.Products.Include(p => p.ProductOptions).FirstOrDefault(p => p.Id == productId);

                if (product == null)
                {
                    return Json(new { success = false, message = "Product not found." });
                }

                if (product.ProductOptions.Any())
                {
                    // Product has options; check for item with specific option and price
                    var existingCartItem = cart.CartItems
                        .FirstOrDefault(ci => ci.ProductId == productId && ci.ProductOptionId == optionId
                                              && (optionPrice == null || ci.Price == optionPrice));

                    if (existingCartItem != null)
                    {
                        // If the item exists, increase the quantity
                        existingCartItem.Quantity += 1;
                    }
                    else
                    {
                        // If the item does not exist, add a new item to the cart
                        var cartItem = new CartItem
                        {
                            Cart = cart,
                            ProductId = productId,
                            ProductOptionId = optionId,
                            Quantity = 1,
                            Price = optionPrice ?? product.Price
                        };
                        _context.CartItems.Add(cartItem);
                    }
                }
                else
                {
                    // Product does not have options; check for item without option
                    var existingCartItem = cart.CartItems
                        .FirstOrDefault(ci => ci.ProductId == productId && ci.ProductOptionId == null);

                    if (existingCartItem != null)
                    {
                        // If the item exists, increase the quantity
                        existingCartItem.Quantity += 1;
                    }
                    else
                    {
                        // If the item does not exist, add a new item to the cart
                        var cartItem = new CartItem
                        {
                            Cart = cart,
                            ProductId = productId,
                            ProductOptionId = null,
                            Quantity = 1,
                            Price = product.Price
                        };
                        _context.CartItems.Add(cartItem);
                    }
                }

                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Product added to cart." });
            }
            return Json(new { success = false, message = "User not found." });
        }




        public async Task<IActionResult> CheackOut()
        {
            var user = await _userManager.GetUserAsync(User);
            string userId = user.Id;

            var userCart = _context.Carts
                .Include(c => c.user)
                .Include(c => c.CartItems)
                    .ThenInclude(ci => ci.Product)
                    .ThenInclude(p => p.ProductOptions)
                .FirstOrDefault(c => c.UserId == userId);

            if (userCart == null)
            {
                return NotFound();
            }

            // Prepare CartViewModel with product options
            var cartViewModel = new CartViewModel
            {
                Email = userCart.user.Email,
                Avatar = userCart.user.Avatar,
                CartItems = userCart.CartItems.Select(ci =>
                {
                    var productOptions = ci.Product.ProductOptions
                        .Where(po => po.OptionPrice == ci.Price)
                        .Select(po => new ProductOptionViewModel
                        {
                            
                            OptionName = po.OptionName,
                            OptionPrice = po.OptionPrice
                        }).ToList();

                    return new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        ProductId = ci.ProductId,
                        ProductName = ci.Product.Name,
                        Quantity = ci.Quantity,
                        Price = ci.Price,
                        Image = ci.Product.Image,
                        ProductOptions = productOptions // Add ProductOptions to the CartItemViewModel
                    };
                }).ToList()
            };

            // Prepare ProductOptions dictionary if needed for other purposes
            var productOptionsDict = userCart.CartItems
                .SelectMany(ci => ci.Product.ProductOptions)
                .Where(po => userCart.CartItems.Any(ci => ci.Price == po.OptionPrice))
                .Distinct()
                .ToDictionary(po => po.Id, po => po.OptionName);

            ViewBag.ProductOptions = productOptionsDict;

            return View(cartViewModel);
        }



    }

}

OnlineOrderingSystem/OnlineOrderingSystem/Views/Carts/CartMenu.cshtml
@model OnlineOrderingSystem.ViewModels.CartViewModel
@{
    Layout = null;
}
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@{
    var afToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}
@* Cart menu *@


<style>
    .cart-container {
        position: absolute;
        padding: 1rem;
        border-radius: 0.375rem;
        box-shadow: 0 3px 10px rgba(0, 0, 0, 0.2);
        background-color: white;
        right: 0px;
        top: -1px;
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
        z-index:20;
    }

    .cart-title {
        font-size: 1.25rem; 
    }

    .list-container {
        display: flex;
        flex-direction: column;
        gap: 2rem; /* Equivalent to gap-8 */
    }

    .item-container {
        display: flex;
        gap: 1rem; /* Equivalent to gap-4 */
    }

    .item-image {
        object-fit: cover;
        border-radius: 0.375rem; /* Equivalent to rounded-md */
    }

    .item-details {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        width: 100%;
    }

    .item-top {
        /* No additional styles needed */
    }

    .item-title-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 2rem; /* Equivalent to gap-8 */
    }

    .item-title {
        font-weight: 600; /* Equivalent to font-semibold */
    }

    .item-price-container {
        padding: 0.25rem; /* Equivalent to p-1 */
        background-color: #f9fafb; /* Equivalent to bg-gray-50 */
        border-radius: 0.125rem; /* Equivalent to rounded-sm */
        display: flex;
        align-items: center;
        gap: 0.5rem; /* Equivalent to gap-2 */
    }

    .item-quantity {
        font-size: 0.75rem; /* Equivalent to text-xs */
        color: #10b981; /* Equivalent to text-green-500 */
    }

    .item-description {
        font-size: 0.875rem; /* Equivalent to text-sm */
        color: #6b7280; /* Equivalent to text-gray-500 */
    }

    .item-bottom {
        display: flex;
        justify-content: space-between;
        font-size: 0.875rem; /* Equivalent to text-sm */
    }

    .item-remove {
        color: #3b82f6; /* Equivalent to text-blue-500 */
        cursor: pointer;
    }

    .subtotal-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        font-weight: 600; /* Equivalent to font-semibold */
    }

    .subtotal-text {
        /* No additional styles needed */
    }

    .shipping-info {
        color: #6b7280; /* Equivalent to text-gray-500 */
        font-size: 0.875rem; /* Equivalent to text-sm */
        margin-top: 0.5rem; /* Equivalent to mt-2 */
        margin-bottom: 1rem; /* Equivalent to mb-4 */
    }

    .button-container {
        display: flex;
        justify-content: space-between;
        font-size: 0.875rem; /* Equivalent to text-sm */
    }

    .view-cart-button {
        border-radius: 0.375rem;
        padding: 0.75rem 1rem;
        border: 1px solid #d1d5db;
        cursor: pointer;
        text-decoration: none;
    }

    .checkout-button {
        border-radius: 0.375rem; /* Equivalent to rounded-md */
        padding: 0.75rem 1rem; /* Equivalent to py-3 px-4 */
        background-color: black;
        color: white;
    }

        .checkout-button:disabled {
            cursor: not-allowed; /* Equivalent to disabled:cursor-not-allowed */
            opacity: 0.75; /* Equivalent to disabled:opacity-75 */
        }

</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />


<div class="cart-container" id="cart-container">
    @if (Model.CartItems.Any())
    {
        <h2 class="cart-title">Shopping Cart</h2>
        <div class="list-container">
            @foreach (var item in Model.CartItems)
            {
                <div class="item-container" key="@item.CartItemId">
                    @if (!string.IsNullOrEmpty(item.Image))
                    {
                        <img src="~/images/@item.Image" alt="" width="72" height="96" class="item-image" />
                    }
                    <div class="item-details">
                        <div class="item-top">
                            <div class="item-title-container">
                                <h3 class="item-title">@item.ProductName</h3>
                                <div class="item-price-container">
                                    @if (item.Quantity > 1)
                                    {
                                        <div class="item-quantity">@item.Quantity x </div>
                                    }
                                    $@item.Price
                                </div>
                            </div>
                        </div>
                        <div class="item-bottom">
                            <span class="item-description">Qty. @item.Quantity</span>
                            <div class="col-2">
                                <a href="#" class="remove-cart-item" data-cart-item-id="@item.CartItemId">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div>
            <div class="subtotal-container">
                <span class="subtotal-text">Subtotal</span>
                <span class="subtotal-text">$@Model.CartItems.Sum(item => item.TotalPrice).ToString("0.00")</span>
            </div>
            <p class="shipping-info">Shipping and taxes calculated at checkout.</p>
            <div class="button-container">
                <a class="view-cart-button" href="@Url.Action("CheackOut","Carts")">View Cart</a>
                <button class="checkout-button">Checkout</button>
            </div>
        </div>
    }
    else
    {
        <div>Cart is Empty</div>
    }

</div>



<script>
    $(document).ready(function () {
        $('.remove-cart-item').on('click', function (e) {
            e.preventDefault();
            var cartItemId = $(this).data('cart-item-id');
            removeCartItem(cartItemId);
        });
    });

    function removeCartItem(cartItemId) {
        $.ajax({
            url: '@Url.Action("RemoveCartItem", "CartItems")',
            type: 'POST',
            data: {
                id: cartItemId,
                __RequestVerificationToken: '@afToken'
            },
            success: function (response) {
                if (response.success) {
                    $('.item-container').filter(function () {
                        return $(this).find('.remove-cart-item').data('cart-item-id') === cartItemId;
                    }).remove();

                    updateSubtotal();
                } else {
                    alert('Error removing cart item.');
                }
            }
        });
    }



    function updateSubtotal() {
        var subtotal = 0;
        $('.item-container').each(function () {
            var priceText = $(this).find('.item-price-container').text().trim();
            var quantityText = $(this).find('.item-quantity').text().trim();
            var quantity = quantityText ? parseInt(quantityText.split('x')[0]) : 1;
            var price = parseFloat(priceText.replace('$', ''));
            subtotal += quantity * price;
        });
        $('.subtotal-text').last().text('$' + subtotal.toFixed(2));
    }
</script>

OnlineOrderingSystem/OnlineOrderingSystem/Views/Carts/CheackOut.cshtml
@model OnlineOrderingSystem.ViewModels.CartViewModel

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@{
    var afToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}
@* //cheackOut Page*@
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-8 cart">
            <div class="title mb-4">
                <div class="row">
                    <div class="col">
                        <h4><b>Shopping Cart</b></h4>
                    </div>
                    <div class="col align-self-center text-right text-muted">
                        @Model.CartItems.Count() items
                    </div>
                </div>
            </div>
            <div class="row border-top border-bottom py-3">
                @Html.AntiForgeryToken()
                @foreach (var item in Model.CartItems)
                {
                    <div class="row main align-items-center mb-5 w-100" data-cart-item-id="@item.CartItemId">
                        <div class="col-2">
                            <img src="~/images/@item.Image" class="img-fluid" alt="@item.ProductName" />
                        </div>
                        <div class="col-4">
                            <div class="row">@item.ProductName</div>
                        </div>
                        <div class="col-2">
                            $<span class="total-price" id="total-price-@item.ProductId">@item.TotalPrice.ToString("0.00")</span>
                        </div>
                        <div class="col-2">
                            <label>Quantity</label>
                            <p>@item.Quantity</p>
                        </div>
                        <div class="col-2 text-right">
                            <a href="#" class="remove-cart-item text-danger" data-cart-item-id="@item.CartItemId">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </div>
                        <div>
                            <label>Options:</label>
                            <ul>
                                @foreach (var option in item.ProductOptions)
                                {
                                    <li>@option.OptionName: $@option.OptionPrice.ToString("0.00")</li>
                                }
                            </ul>
                        </div>
                    </div>
                
                }
            </div>
            <div class="back-to-shop mt-3">
                <a asp-area="" asp-controller="Home" asp-action="HomePage" class="btn btn-outline-secondary">
                    <i class="fas fa-arrow-left"></i> Back to shop
                </a>
            </div>
        </div>
        <div class="col-md-8 summary mt-5">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="@Model.Avatar" alt="User Avatar" class="img-fluid rounded-circle">
                        </div>
                        <div class="col-9 text-right">
                            <div class="row">
                                <div class="col">USER EMAIL</div>
                                <div class="col">@Model.Email</div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="payment-methods">
                        <div class="bg-white shadow-sm p-3 mb-3">
                            <ul role="tablist" class="nav nav-pills nav-fill">
                                <li class="nav-item">
                                    <input type="radio" id="credit-card-radio" name="selectedPaymentMethod" value="credit-card" checked>
                                    <label for="credit-card-radio" class="nav-link active"><i class="fas fa-credit-card mr-2"></i> Credit Card</label>
                                </li>
                                <li class="nav-item">
                                    <input type="radio" id="paypal-radio" name="selectedPaymentMethod" value="paypal">
                                    <label for="paypal-radio" class="nav-link"><i class="fab fa-paypal mr-2"></i> Paypal</label>
                                </li>
                                <li class="nav-item">
                                    <input type="radio" id="cash-radio" name="selectedPaymentMethod" value="cash">
                                    <label for="cash-radio" class="nav-link"><i class="fas fa-mobile-alt mr-2"></i> Cash</label>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div id="credit-card" class="tab-pane fade">
                                <p>Credit card payment content</p>
                            </div>
                            <div id="paypal" class="tab-pane fade">
                                <p>Paypal payment content</p>
                            </div>
                            <div id="net-banking" class="tab-pane fade">
                                <p>Bank transfer payment content</p>
                            </div>
                        </div>
                    </div>
                    <a id="checkoutBtn" class="btn btn-secondary btn-block mt-4">
                        Checkout - $@Model.CartItems.Sum(item => item.TotalPrice).ToString("0.00")
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .cart .title h4 {
        margin-bottom: 0;
    }

    .cart .main {
        padding: 15px 0;
    }

        .cart .main img {
            max-height: 100px;
        }

        .cart .main .total-price {
            font-weight: bold;
        }

    .cart .back-to-shop {
        margin-top: 20px;
    }

    .summary .avatar {
        max-height: 50px;
    }

    .summary .payment-methods .nav-link {
        display: flex;
        align-items: center;
        justify-content: center;
    }

        .summary .payment-methods .nav-link.active {
            background-color: #007bff;
            color: white;
        }
</style>



    <script>



        $('.remove-cart-item').on('click', function (e) {
            e.preventDefault();
            var cartItemId = $(this).data('cart-item-id');
            removeCartItem(cartItemId);
        });

        function updateCartItem(cartItemId, quantity) {
            $.ajax({
                url: '@Url.Action("UpdateCartItem", "CartItems")',
                type: 'POST',
                data: {
                    id: cartItemId,
                    quantity: quantity,
                    __RequestVerificationToken: '@afToken'
                },
                success: function (response) {
                    if (response.success) {

                    } else {
                        alert('Error updating cart item.');
                    }
                }
            });
        }

        function removeCartItem(cartItemId) {
            $.ajax({
                url: '@Url.Action("RemoveCartItem", "CartItems")',
                type: 'POST',
                data: {
                    id: cartItemId,
                    __RequestVerificationToken: '@afToken'
                },
                success: function (response) {
                    if (response.success) {
                        $('div[data-cart-item-id="' + cartItemId + '"]').remove();

                    } else {
                        alert('Error removing cart item.');
                    }
                }
            });
        }


        $('#checkoutBtn').click(function () {
            var selectedPMethod = $('input[name="selectedPaymentMethod"]:checked').val();
            if (selectedPMethod) {
                $.ajax({
                    url: 'Checkout/Carts?' + 'selectedPaymentMethod=' + selectedPMethod,
                    method: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify({ selectedPaymentMethod: selectedPMethod }),
                    success: function (response) {
                        if (response.orderId) {
                            
                            window.location.href = '/Orders/OrderDetails/' + response.orderId;
                        } else {
                            console.error('Order ID not found in response.');
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error('There was a problem with the AJAX request:', selectedPMethod);
                    }
                });
            } else {
                alert('Please select a payment method.');
            }
        });


    </script>